version: "3.3"

services:
  pet-store:
    image: ghcr.io/nadundesilva/samples/pet-store:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080:8080"
