version: "3.3"

services:
  pet-store:
    image: ghcr.io/nadundesilva/samples/pet-store:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080:8080"
    depends_on:
    - database

  database:
    image: mysql:8.0.27
    ports:
    - "33060"
    volumes:
    - ${PWD}/pet_store.sql:/docker-entrypoint-initdb.d/pet_store.sql
    environment:
    - MYSQL_ROOT_PASSWORD=pet-store-root
    - MYSQL_USER=pet-store-user
    - MYSQL_PASSWORD=pet-store-user-password
    - MYSQL_DATABASE=pet_store
