version: "3.3"

services:
  pet-store-api:
    image: ghcr.io/nadundesilva/samples/pet-store/main:${VERSION}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080:8080"
    depends_on:
    - pets-api
    - jaeger
    environment:
    - PET_STORE_PACKAGE=pet_store
    - WAIT_FOR=tcp://pet-api:8080
    - PETS_API_HOST=pets-api
    - PETS_API_PORT=8080

  pets-api:
    image: ghcr.io/nadundesilva/samples/pet-store/main:${VERSION}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8090:8080"
    depends_on:
    - database
    - jaeger
    environment:
    - PET_STORE_PACKAGE=pets
    - WAIT_FOR=tcp://database:3306
    - DATABASE_URL=mysql+pymysql://pet-store-user:pet-store-user-password@database:3306/pet_store

  database:
    image: mysql:8.0.27
    ports:
    - "3306"
    volumes:
    - ${PWD}/db_scripts:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_ROOT_PASSWORD=pet-store-root
    - MYSQL_USER=pet-store-user
    - MYSQL_PASSWORD=pet-store-user-password
    - MYSQL_DATABASE=pet_store

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
    - "55680"
    - "16686:16686"
