version: "3.3"

services:
  pet-store:
    image: ghcr.io/nadundesilva/samples/pet-store/main:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080:8080"
    depends_on:
    - database
    - jaeger
    environment:
    - PET_STORE_PACKAGE=pet_store
    - WAIT_FOR=tcp://database:33060
    - DATABASE_URL=mysql://pet-store-user:pet-store-user-password@database:33060/pet_store

  database:
    image: mysql:8.0.27
    ports:
    - "33060"
    volumes:
    - ${PWD}/pet_store.sql:/docker-entrypoint-initdb.d/pet_store.sql
    environment:
    - MYSQL_ROOT_PASSWORD=pet-store-root
    - MYSQL_USER=pet-store-user
    - MYSQL_PASSWORD=pet-store-user-password
    - MYSQL_DATABASE=pet_store

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
    - "55680"
    - "16686:16686"
