version: "3.3"

services:
  data-generator:
    image: ghcr.io/nadundesilva/samples/pet-store/data-generator:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/data_generator/Dockerfile
    cap_drop:
    - ALL
    depends_on:
    - pet-store-api
    - otel-collector
    environment:
    - OTEL_PYTHON_LOG_LEVEL=DEBUG
    - PET_STORE_API_TCP_ADDRESS=tcp://pet-store-api:8080
    - PET_STORE_API_BASE_URL=http://pet-store-api:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  pet-store-api:
    image: ghcr.io/nadundesilva/samples/pet-store/main:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080:8080"
    depends_on:
    - pets-api
    - customers-api
    - orders-api
    - otel-collector
    environment:
    - PET_STORE_PACKAGE=pet_store
    - WAIT_FOR=tcp://pets-api:8080,tcp://customers-api:8080,tcp://orders-api:8080
    - OTEL_PYTHON_LOG_LEVEL=DEBUG
    - PETS_API_BASE_URL=http://pets-api:8080
    - CUSTOMERS_API_BASE_URL=http://customers-api:8080
    - ORDERS_API_BASE_URL=http://orders-api:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  pets-api:
    image: ghcr.io/nadundesilva/samples/pet-store/main:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080"
    depends_on:
    - database
    - otel-collector
    environment:
    - PET_STORE_PACKAGE=pets
    - WAIT_FOR=tcp://database:3306
    - OTEL_PYTHON_LOG_LEVEL=DEBUG
    - DATABASE_URL=mysql+pymysql://pet-store-user:pet-store-user-password@database:3306/pet_store
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  customers-api:
    image: ghcr.io/nadundesilva/samples/pet-store/main:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080"
    depends_on:
    - database
    - otel-collector
    environment:
    - PET_STORE_PACKAGE=customers
    - WAIT_FOR=tcp://database:3306
    - OTEL_PYTHON_LOG_LEVEL=DEBUG
    - DATABASE_URL=mysql+pymysql://pet-store-user:pet-store-user-password@database:3306/pet_store
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  orders-api:
    image: ghcr.io/nadundesilva/samples/pet-store/main:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/pet_store/Dockerfile
    cap_drop:
    - ALL
    ports:
    - "8080"
    depends_on:
    - database
    - otel-collector
    environment:
    - PET_STORE_PACKAGE=orders
    - WAIT_FOR=tcp://database:3306
    - OTEL_PYTHON_LOG_LEVEL=DEBUG
    - DATABASE_URL=mysql+pymysql://pet-store-user:pet-store-user-password@database:3306/pet_store
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317

  database:
    image: mysql:8.0.27
    ports:
    - "3306"
    volumes:
    - ${PWD}/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    environment:
    - MYSQL_ROOT_PASSWORD=pet-store-root
    - MYSQL_USER=pet-store-user
    - MYSQL_PASSWORD=pet-store-user-password
    - MYSQL_DATABASE=pet_store

  otel-collector:
    image: otel/opentelemetry-collector:0.38.0
    command: ["otelcol", "--config", "/etc/otel-collector/otel-config.yaml"]
    ports:
    - "4317"
    depends_on:
    - jaeger
    volumes:
    - "${PWD}/otel-config.yaml:/etc/otel-collector/otel-config.yaml"

  jaeger:
    image: jaegertracing/all-in-one:1.28
    ports:
    - "14250"
    - "16686:16686"
