version: "3.3"

services:
  data-generator:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: data-generator

  pet-store-api:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: pet-store-api

  pets-api:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: pets-api

  customers-api:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: customers-api

  orders-api:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: orders-api

  database:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: basebase

  otel-collector:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: basebase

  jaeger:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: basebase
